=begin
#An example of generating swagger via gRPC ecosystem.

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Contact: none@example.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

module OpenapiClient
  VERSION = '1.0.0'
end
