/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CheckResponseServingStatus = {
    UnknownUnspecified: 'SERVING_STATUS_UNKNOWN_UNSPECIFIED',
    Serving: 'SERVING_STATUS_SERVING',
    NotServing: 'SERVING_STATUS_NOT_SERVING'
} as const;
export type CheckResponseServingStatus = typeof CheckResponseServingStatus[keyof typeof CheckResponseServingStatus];


export function CheckResponseServingStatusFromJSON(json: any): CheckResponseServingStatus {
    return CheckResponseServingStatusFromJSONTyped(json, false);
}

export function CheckResponseServingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckResponseServingStatus {
    return json as CheckResponseServingStatus;
}

export function CheckResponseServingStatusToJSON(value?: CheckResponseServingStatus | null): any {
    return value as any;
}

