/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProtoRequest
 */
export interface ProtoRequest {
    /**
     * 
     * @type {string}
     * @memberof ProtoRequest
     */
    id?: string;
}

export function ProtoRequestFromJSON(json: any): ProtoRequest {
    return ProtoRequestFromJSONTyped(json, false);
}

export function ProtoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ProtoRequestToJSON(value?: ProtoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


