/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RpcCode,
    RpcCodeFromJSON,
    RpcCodeFromJSONTyped,
    RpcCodeToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProtoResponse
 */
export interface ProtoResponse {
    /**
     * 
     * @type {RpcCode}
     * @memberof ProtoResponse
     */
    code?: RpcCode;
    /**
     * 
     * @type {string}
     * @memberof ProtoResponse
     */
    message?: string;
}

export function ProtoResponseFromJSON(json: any): ProtoResponse {
    return ProtoResponseFromJSONTyped(json, false);
}

export function ProtoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : RpcCodeFromJSON(json['code']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ProtoResponseToJSON(value?: ProtoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': RpcCodeToJSON(value.code),
        'message': value.message,
    };
}


