/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcStatus } from './RpcStatus';
import {
    RpcStatusFromJSON,
    RpcStatusFromJSONTyped,
    RpcStatusToJSON,
} from './RpcStatus';
import type { V1HealthCheckResponse } from './V1HealthCheckResponse';
import {
    V1HealthCheckResponseFromJSON,
    V1HealthCheckResponseFromJSONTyped,
    V1HealthCheckResponseToJSON,
} from './V1HealthCheckResponse';

/**
 * 
 * @export
 * @interface StreamResultOfV1HealthCheckResponse
 */
export interface StreamResultOfV1HealthCheckResponse {
    /**
     * 
     * @type {V1HealthCheckResponse}
     * @memberof StreamResultOfV1HealthCheckResponse
     */
    result?: V1HealthCheckResponse;
    /**
     * 
     * @type {RpcStatus}
     * @memberof StreamResultOfV1HealthCheckResponse
     */
    error?: RpcStatus;
}

/**
 * Check if a given object implements the StreamResultOfV1HealthCheckResponse interface.
 */
export function instanceOfStreamResultOfV1HealthCheckResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StreamResultOfV1HealthCheckResponseFromJSON(json: any): StreamResultOfV1HealthCheckResponse {
    return StreamResultOfV1HealthCheckResponseFromJSONTyped(json, false);
}

export function StreamResultOfV1HealthCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamResultOfV1HealthCheckResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : V1HealthCheckResponseFromJSON(json['result']),
        'error': !exists(json, 'error') ? undefined : RpcStatusFromJSON(json['error']),
    };
}

export function StreamResultOfV1HealthCheckResponseToJSON(value?: StreamResultOfV1HealthCheckResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': V1HealthCheckResponseToJSON(value.result),
        'error': RpcStatusToJSON(value.error),
    };
}

