/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ServingStatus } from './V1ServingStatus';
import {
    V1ServingStatusFromJSON,
    V1ServingStatusFromJSONTyped,
    V1ServingStatusToJSON,
    V1ServingStatusToJSONTyped,
} from './V1ServingStatus';

/**
 * The response message containing the health status of the service.
 * @export
 * @interface V1CheckResponse
 */
export interface V1CheckResponse {
    /**
     * 
     * @type {V1ServingStatus}
     * @memberof V1CheckResponse
     */
    status: V1ServingStatus;
}



/**
 * Check if a given object implements the V1CheckResponse interface.
 */
export function instanceOfV1CheckResponse(value: object): value is V1CheckResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function V1CheckResponseFromJSON(json: any): V1CheckResponse {
    return V1CheckResponseFromJSONTyped(json, false);
}

export function V1CheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': V1ServingStatusFromJSON(json['status']),
    };
}

export function V1CheckResponseToJSON(json: any): V1CheckResponse {
    return V1CheckResponseToJSONTyped(json, false);
}

export function V1CheckResponseToJSONTyped(value?: V1CheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': V1ServingStatusToJSON(value['status']),
    };
}

