/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Protov1Status } from './Protov1Status';
import {
    Protov1StatusFromJSON,
    Protov1StatusFromJSONTyped,
    Protov1StatusToJSON,
    Protov1StatusToJSONTyped,
} from './Protov1Status';

/**
 * 
 * @export
 * @interface V1ExampleServiceQueryResponse
 */
export interface V1ExampleServiceQueryResponse {
    /**
     * 
     * @type {Protov1Status}
     * @memberof V1ExampleServiceQueryResponse
     */
    status?: Protov1Status;
}

/**
 * Check if a given object implements the V1ExampleServiceQueryResponse interface.
 */
export function instanceOfV1ExampleServiceQueryResponse(value: object): value is V1ExampleServiceQueryResponse {
    return true;
}

export function V1ExampleServiceQueryResponseFromJSON(json: any): V1ExampleServiceQueryResponse {
    return V1ExampleServiceQueryResponseFromJSONTyped(json, false);
}

export function V1ExampleServiceQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ExampleServiceQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : Protov1StatusFromJSON(json['status']),
    };
}

export function V1ExampleServiceQueryResponseToJSON(json: any): V1ExampleServiceQueryResponse {
    return V1ExampleServiceQueryResponseToJSONTyped(json, false);
}

export function V1ExampleServiceQueryResponseToJSONTyped(value?: V1ExampleServiceQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': Protov1StatusToJSON(value['status']),
    };
}

