/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Protov1Status } from './Protov1Status';
import {
    Protov1StatusFromJSON,
    Protov1StatusFromJSONTyped,
    Protov1StatusToJSON,
} from './Protov1Status';

/**
 * 
 * @export
 * @interface V1ExampleServiceQueryResponse
 */
export interface V1ExampleServiceQueryResponse {
    /**
     * 
     * @type {Protov1Status}
     * @memberof V1ExampleServiceQueryResponse
     */
    status?: Protov1Status;
}

/**
 * Check if a given object implements the V1ExampleServiceQueryResponse interface.
 */
export function instanceOfV1ExampleServiceQueryResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ExampleServiceQueryResponseFromJSON(json: any): V1ExampleServiceQueryResponse {
    return V1ExampleServiceQueryResponseFromJSONTyped(json, false);
}

export function V1ExampleServiceQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ExampleServiceQueryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : Protov1StatusFromJSON(json['status']),
    };
}

export function V1ExampleServiceQueryResponseToJSON(value?: V1ExampleServiceQueryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': Protov1StatusToJSON(value.status),
    };
}

