/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Protov1Response,
    Protov1ResponseFromJSON,
    Protov1ResponseFromJSONTyped,
    Protov1ResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface V1HealthCheckServiceHealthCheckResponse
 */
export interface V1HealthCheckServiceHealthCheckResponse {
    /**
     * 
     * @type {Protov1Response}
     * @memberof V1HealthCheckServiceHealthCheckResponse
     */
    value?: Protov1Response;
}

export function V1HealthCheckServiceHealthCheckResponseFromJSON(json: any): V1HealthCheckServiceHealthCheckResponse {
    return V1HealthCheckServiceHealthCheckResponseFromJSONTyped(json, false);
}

export function V1HealthCheckServiceHealthCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1HealthCheckServiceHealthCheckResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : Protov1ResponseFromJSON(json['value']),
    };
}

export function V1HealthCheckServiceHealthCheckResponseToJSON(value?: V1HealthCheckServiceHealthCheckResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': Protov1ResponseToJSON(value.value),
    };
}


