/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1ServingStatus = {
    ServingStatusUnknownUnspecified: 'SERVING_STATUS_UNKNOWN_UNSPECIFIED',
    ServingStatusServing: 'SERVING_STATUS_SERVING',
    ServingStatusNotServing: 'SERVING_STATUS_NOT_SERVING'
} as const;
export type V1ServingStatus = typeof V1ServingStatus[keyof typeof V1ServingStatus];


export function instanceOfV1ServingStatus(value: any): boolean {
    for (const key in V1ServingStatus) {
        if (Object.prototype.hasOwnProperty.call(V1ServingStatus, key)) {
            if (V1ServingStatus[key as keyof typeof V1ServingStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function V1ServingStatusFromJSON(json: any): V1ServingStatus {
    return V1ServingStatusFromJSONTyped(json, false);
}

export function V1ServingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ServingStatus {
    return json as V1ServingStatus;
}

export function V1ServingStatusToJSON(value?: V1ServingStatus | null): any {
    return value as any;
}

export function V1ServingStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): V1ServingStatus {
    return value as V1ServingStatus;
}

