# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.example_service_api import ExampleServiceApi


class TestExampleServiceApi(unittest.TestCase):
    """ExampleServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExampleServiceApi()

    def tearDown(self) -> None:
        pass

    def test_example_service_query(self) -> None:
        """Test case for example_service_query

        """
        pass


if __name__ == '__main__':
    unittest.main()
