# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.health_check_response_serving_status import HealthCheckResponseServingStatus  # noqa: E501

class TestHealthCheckResponseServingStatus(unittest.TestCase):
    """HealthCheckResponseServingStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthCheckResponseServingStatus(self):
        """Test HealthCheckResponseServingStatus"""
        # inst = HealthCheckResponseServingStatus()

if __name__ == '__main__':
    unittest.main()
