# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.health_check_service_api import HealthCheckServiceApi  # noqa: E501


class TestHealthCheckServiceApi(unittest.TestCase):
    """HealthCheckServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthCheckServiceApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_health_check(self) -> None:
        """Test case for health_check

        """
        pass


if __name__ == '__main__':
    unittest.main()
