# coding: utf-8

"""
    proto/helthcheck.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.gateway_health_check_response import GatewayHealthCheckResponse  # noqa: E501
from openapi_client.rest import ApiException


class TestGatewayHealthCheckResponse(unittest.TestCase):
    """GatewayHealthCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGatewayHealthCheckResponse(self):
        """Test GatewayHealthCheckResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.gateway_health_check_response.GatewayHealthCheckResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
