# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.proto_response import ProtoResponse  # noqa: E501
from openapi_client.rest import ApiException


class TestProtoResponse(unittest.TestCase):
    """ProtoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtoResponse(self):
        """Test ProtoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.proto_response.ProtoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
