# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v1_health_check_service_health_check_response import V1HealthCheckServiceHealthCheckResponse  # noqa: E501

class TestV1HealthCheckServiceHealthCheckResponse(unittest.TestCase):
    """V1HealthCheckServiceHealthCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1HealthCheckServiceHealthCheckResponse:
        """Test V1HealthCheckServiceHealthCheckResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1HealthCheckServiceHealthCheckResponse`
        """
        model = V1HealthCheckServiceHealthCheckResponse()  # noqa: E501
        if include_optional:
            return V1HealthCheckServiceHealthCheckResponse(
                value = openapi_client.models.protov1_response.protov1Response(
                    code = 'OK', 
                    message = '', )
            )
        else:
            return V1HealthCheckServiceHealthCheckResponse(
        )
        """

    def testV1HealthCheckServiceHealthCheckResponse(self):
        """Test V1HealthCheckServiceHealthCheckResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
