# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v1_example_service_query_request import V1ExampleServiceQueryRequest  # noqa: E501

class TestV1ExampleServiceQueryRequest(unittest.TestCase):
    """V1ExampleServiceQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExampleServiceQueryRequest:
        """Test V1ExampleServiceQueryRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExampleServiceQueryRequest`
        """
        model = V1ExampleServiceQueryRequest()  # noqa: E501
        if include_optional:
            return V1ExampleServiceQueryRequest(
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC0'
            )
        else:
            return V1ExampleServiceQueryRequest(
        )
        """

    def testV1ExampleServiceQueryRequest(self):
        """Test V1ExampleServiceQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
