# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_check_response import V1CheckResponse

class TestV1CheckResponse(unittest.TestCase):
    """V1CheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CheckResponse:
        """Test V1CheckResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CheckResponse`
        """
        model = V1CheckResponse()
        if include_optional:
            return V1CheckResponse(
                status = 'SERVING_STATUS_UNKNOWN_UNSPECIFIED'
            )
        else:
            return V1CheckResponse(
                status = 'SERVING_STATUS_UNKNOWN_UNSPECIFIED',
        )
        """

    def testV1CheckResponse(self):
        """Test V1CheckResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
