# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.proto_response import ProtoResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestProtoResponse(unittest.TestCase):
    """ProtoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProtoResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.proto_response.ProtoResponse()  # noqa: E501
        if include_optional :
            return ProtoResponse(
                code = 'OK', 
                message = '0'
            )
        else :
            return ProtoResponse(
        )

    def testProtoResponse(self):
        """Test ProtoResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
