# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v1_example_service_query_response import V1ExampleServiceQueryResponse  # noqa: E501

class TestV1ExampleServiceQueryResponse(unittest.TestCase):
    """V1ExampleServiceQueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExampleServiceQueryResponse:
        """Test V1ExampleServiceQueryResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExampleServiceQueryResponse`
        """
        model = V1ExampleServiceQueryResponse()  # noqa: E501
        if include_optional:
            return V1ExampleServiceQueryResponse(
                status = openapi_client.models.extends_[rfc_9457]_for_api_response/
rfc_9457___problem_details_for_http_apis_https://datatracker/ietf/org/doc/html/rfc9457.Extends [RFC 9457] for API response.
RFC 9457 - Problem Details for HTTP APIs https://datatracker.ietf.org/doc/html/rfc9457(
                    type = '', 
                    status = 56, 
                    title = '', 
                    detail = '', 
                    instance = '', 
                    extensions = [
                        ''
                        ], 
                    code = 'OK', )
            )
        else:
            return V1ExampleServiceQueryResponse(
        )
        """

    def testV1ExampleServiceQueryResponse(self):
        """Test V1ExampleServiceQueryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
