# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1/health.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/v1/health.proto\x12\x08proto.v1\x1a\x1cgoogle/api/annotations.proto\".\n\x12HealthCheckRequest\x12\x18\n\x07service\x18\x01 \x01(\tR\x07service\"\xab\x01\n\x13HealthCheckResponse\x12\x43\n\x06status\x18\x01 \x01(\x0e\x32+.proto.v1.HealthCheckResponse.ServingStatusR\x06status\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\x32\xc2\x01\n\x06Health\x12Z\n\x05\x43heck\x12\x1c.proto.v1.HealthCheckRequest\x1a\x1d.proto.v1.HealthCheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/healthCheck\x12\\\n\x05Watch\x12\x1c.proto.v1.HealthCheckRequest\x1a\x1d.proto.v1.HealthCheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/healthWatch0\x01\x42i\n\x0c\x63om.proto.v1B\x0bHealthProtoP\x01Z\x0bpb/proto/v1\xa2\x02\x03PXX\xaa\x02\x08Proto.V1\xca\x02\x08Proto\\V1\xe2\x02\x14Proto\\V1\\GPBMetadata\xea\x02\tProto::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.v1.health_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014com.proto.v1B\013HealthProtoP\001Z\013pb/proto/v1\242\002\003PXX\252\002\010Proto.V1\312\002\010Proto\\V1\342\002\024Proto\\V1\\GPBMetadata\352\002\tProto::V1'
  _HEALTH.methods_by_name['Check']._options = None
  _HEALTH.methods_by_name['Check']._serialized_options = b'\202\323\344\223\002\016\022\014/healthCheck'
  _HEALTH.methods_by_name['Watch']._options = None
  _HEALTH.methods_by_name['Watch']._serialized_options = b'\202\323\344\223\002\016\022\014/healthWatch'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=65
  _globals['_HEALTHCHECKREQUEST']._serialized_end=111
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=114
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=285
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=206
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=285
  _globals['_HEALTH']._serialized_start=288
  _globals['_HEALTH']._serialized_end=482
# @@protoc_insertion_point(module_scope)
