# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1/helthcheck.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.v1 import message_pb2 as proto_dot_v1_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/v1/helthcheck.proto\x12\x08proto.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16proto/v1/message.proto\"Q\n%HealthCheckServiceHealthCheckResponse\x12(\n\x05value\x18\x01 \x01(\x0b\x32\x12.proto.v1.ResponseR\x05value2\x82\x01\n\x12HealthCheckService\x12l\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a/.proto.v1.HealthCheckServiceHealthCheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/healthCheckBm\n\x0c\x63om.proto.v1B\x0fHelthcheckProtoP\x01Z\x0bpb/proto/v1\xa2\x02\x03PXX\xaa\x02\x08Proto.V1\xca\x02\x08Proto\\V1\xe2\x02\x14Proto\\V1\\GPBMetadata\xea\x02\tProto::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.v1.helthcheck_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014com.proto.v1B\017HelthcheckProtoP\001Z\013pb/proto/v1\242\002\003PXX\252\002\010Proto.V1\312\002\010Proto\\V1\342\002\024Proto\\V1\\GPBMetadata\352\002\tProto::V1'
  _HEALTHCHECKSERVICE.methods_by_name['HealthCheck']._options = None
  _HEALTHCHECKSERVICE.methods_by_name['HealthCheck']._serialized_options = b'\202\323\344\223\002\016\022\014/healthCheck'
  _HEALTHCHECKSERVICEHEALTHCHECKRESPONSE._serialized_start=122
  _HEALTHCHECKSERVICEHEALTHCHECKRESPONSE._serialized_end=203
  _HEALTHCHECKSERVICE._serialized_start=206
  _HEALTHCHECKSERVICE._serialized_end=336
# @@protoc_insertion_point(module_scope)
