# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1/message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.mwitkow.go_proto_validators import validator_pb2 as github_dot_com_dot_mwitkow_dot_go__proto__validators_dot_validator__pb2
from google.rpc import code_pb2 as google_dot_rpc_dot_code__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/v1/message.proto',
  package='proto.v1',
  syntax='proto3',
  serialized_options=b'Z\013pb/proto/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16proto/v1/message.proto\x12\x08proto.v1\x1a\x36github.com/mwitkow/go-proto-validators/validator.proto\x1a\x15google/rpc/code.proto\"D\n\x08Response\x12\'\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x10.google.rpc.CodeB\x07\xe2\xdf\x1f\x03\x88\x01\x01\x12\x0f\n\x07message\x18\x02 \x01(\tB\rZ\x0bpb/proto/v1b\x06proto3'
  ,
  dependencies=[github_dot_com_dot_mwitkow_dot_go__proto__validators_dot_validator__pb2.DESCRIPTOR,google_dot_rpc_dot_code__pb2.DESCRIPTOR,])




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='proto.v1.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='proto.v1.Response.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\337\037\003\210\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.v1.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=183,
)

_RESPONSE.fields_by_name['code'].enum_type = google_dot_rpc_dot_code__pb2._CODE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'proto.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:proto.v1.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None
_RESPONSE.fields_by_name['code']._options = None
# @@protoc_insertion_point(module_scope)
