# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1/option.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoc_gen_swagger.options import annotations_pb2 as protoc__gen__swagger_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/v1/option.proto',
  package='proto.v1',
  syntax='proto3',
  serialized_options=b'Z\013pb/proto/v1\222A\216\004\022\275\001\n4An example of generating swagger via gRPC ecosystem.\"8\022$https://github.com/michilu/proto-api\032\020none@example.com*F\n\nApache-2.0\0228https://github.com/michilu/proto-api/blob/master/LICENSE2\0031.0*\002\002\0042\020application/json:\020application/jsonZ\370\001\n\035\n\nApiKeyAuth\022\017\010\002\032\tX-API-Key \002\n\326\001\n\006OAuth2\022\313\001\010\003(\0042#https://example.com/oauth/authorize:\037https://example.com/oauth/tokenB\177\n\032\n\004read\022\022Grants read access\n\034\n\005write\022\023Grants write access\nC\n\005admin\022:Grants read and write access to administrative informationb)\n\027\n\006OAuth2\022\r\n\004read\n\005write\n\016\n\nApiKeyAuth\022\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proto/v1/option.proto\x12\x08proto.v1\x1a,protoc-gen-swagger/options/annotations.protoB\x9f\x04Z\x0bpb/proto/v1\x92\x41\x8e\x04\x12\xbd\x01\n4An example of generating swagger via gRPC ecosystem.\"8\x12$https://github.com/michilu/proto-api\x1a\x10none@example.com*F\n\nApache-2.0\x12\x38https://github.com/michilu/proto-api/blob/master/LICENSE2\x03\x31.0*\x02\x02\x04\x32\x10\x61pplication/json:\x10\x61pplication/jsonZ\xf8\x01\n\x1d\n\nApiKeyAuth\x12\x0f\x08\x02\x1a\tX-API-Key \x02\n\xd6\x01\n\x06OAuth2\x12\xcb\x01\x08\x03(\x04\x32#https://example.com/oauth/authorize:\x1fhttps://example.com/oauth/tokenB\x7f\n\x1a\n\x04read\x12\x12Grants read access\n\x1c\n\x05write\x12\x13Grants write access\nC\n\x05\x61\x64min\x12:Grants read and write access to administrative informationb)\n\x17\n\x06OAuth2\x12\r\n\x04read\n\x05write\n\x0e\n\nApiKeyAuth\x12\x00\x62\x06proto3'
  ,
  dependencies=[protoc__gen__swagger_dot_options_dot_annotations__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
