# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/v1/option.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/v1/option.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/v1/option.proto\x12\x08proto.v1\x1a.protoc-gen-openapiv2/options/annotations.protoB\x8c\x05\n\x0c\x63om.proto.v1B\x0bOptionProtoP\x01Z\x0c\x61pi/proto/v1\xa2\x02\x03PXX\xaa\x02\x08Proto.V1\xca\x02\x08Proto\\V1\xe2\x02\x14Proto\\V1\\GPBMetadata\xea\x02\tProto::V1\x92\x41\x9e\x04\x12\xbd\x01\n4An example of generating swagger via gRPC ecosystem.\"8\x12$https://github.com/michilu/proto-api\x1a\x10none@example.com*F\n\nApache-2.0\x12\x38https://github.com/michilu/proto-api/blob/master/LICENSE2\x03\x31.0\x1a\x0elocalhost:3100*\x02\x01\x02\x32\x10\x61pplication/json:\x10\x61pplication/jsonZ\xf8\x01\n\x1d\n\nApiKeyAuth\x12\x0f\x08\x02\x1a\tX-API-Key \x02\n\xd6\x01\n\x06OAuth2\x12\xcb\x01\x08\x03(\x04\x32#https://example.com/oauth/authorize:\x1fhttps://example.com/oauth/tokenB\x7f\nC\n\x05\x61\x64min\x12:Grants read and write access to administrative information\n\x1a\n\x04read\x12\x12Grants read access\n\x1c\n\x05write\x12\x13Grants write accessb)\n\x0e\n\nApiKeyAuth\x12\x00\n\x17\n\x06OAuth2\x12\r\n\x04read\n\x05writeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.v1.option_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.proto.v1B\013OptionProtoP\001Z\014api/proto/v1\242\002\003PXX\252\002\010Proto.V1\312\002\010Proto\\V1\342\002\024Proto\\V1\\GPBMetadata\352\002\tProto::V1\222A\236\004\022\275\001\n4An example of generating swagger via gRPC ecosystem.\"8\022$https://github.com/michilu/proto-api\032\020none@example.com*F\n\nApache-2.0\0228https://github.com/michilu/proto-api/blob/master/LICENSE2\0031.0\032\016localhost:3100*\002\001\0022\020application/json:\020application/jsonZ\370\001\n\035\n\nApiKeyAuth\022\017\010\002\032\tX-API-Key \002\n\326\001\n\006OAuth2\022\313\001\010\003(\0042#https://example.com/oauth/authorize:\037https://example.com/oauth/tokenB\177\nC\n\005admin\022:Grants read and write access to administrative information\n\032\n\004read\022\022Grants read access\n\034\n\005write\022\023Grants write accessb)\n\016\n\nApiKeyAuth\022\000\n\027\n\006OAuth2\022\r\n\004read\n\005write'
# @@protoc_insertion_point(module_scope)
