# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from proto.v1 import message_pb2 as proto_dot_v1_dot_message__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/v1/service.proto\x12\x08proto.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16proto/v1/message.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\x9c\x01\n\x1a\x45xampleServiceQueryRequest\x12~\n\x02id\x18\x01 \x01(\tBn\xfa\x42\x05r\x03\xb0\x01\x01\x92\x41\x63\x80\x01\x01\x8a\x01V^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$\xa2\x02\x04uuidR\x02id\"G\n\x1b\x45xampleServiceQueryResponse\x12(\n\x05value\x18\x01 \x01(\x0b\x32\x12.proto.v1.ResponseR\x05value2\xb0\x01\n\x0e\x45xampleService\x12\x9d\x01\n\x05Query\x12$.proto.v1.ExampleServiceQueryRequest\x1a%.proto.v1.ExampleServiceQueryResponse\"G\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/example/{id}\x92\x41)b\'\n\x0c\n\nApiKeyAuth\n\x17\n\x06OAuth2\x12\r\n\x04read\n\x05writeBj\n\x0c\x63om.proto.v1B\x0cServiceProtoP\x01Z\x0bpb/proto/v1\xa2\x02\x03PXX\xaa\x02\x08Proto.V1\xca\x02\x08Proto\\V1\xe2\x02\x14Proto\\V1\\GPBMetadata\xea\x02\tProto::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.v1.service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014com.proto.v1B\014ServiceProtoP\001Z\013pb/proto/v1\242\002\003PXX\252\002\010Proto.V1\312\002\010Proto\\V1\342\002\024Proto\\V1\\GPBMetadata\352\002\tProto::V1'
  _EXAMPLESERVICEQUERYREQUEST.fields_by_name['id']._options = None
  _EXAMPLESERVICEQUERYREQUEST.fields_by_name['id']._serialized_options = b'\372B\005r\003\260\001\001\222Ac\200\001\001\212\001V^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$\242\002\004uuid'
  _EXAMPLESERVICE.methods_by_name['Query']._options = None
  _EXAMPLESERVICE.methods_by_name['Query']._serialized_options = b'\202\323\344\223\002\025:\001*\"\020/v1/example/{id}\222A)b\'\n\014\n\nApiKeyAuth\n\027\n\006OAuth2\022\r\n\004read\n\005write'
  _EXAMPLESERVICEQUERYREQUEST._serialized_start=164
  _EXAMPLESERVICEQUERYREQUEST._serialized_end=320
  _EXAMPLESERVICEQUERYRESPONSE._serialized_start=322
  _EXAMPLESERVICEQUERYRESPONSE._serialized_end=393
  _EXAMPLESERVICE._serialized_start=396
  _EXAMPLESERVICE._serialized_end=572
# @@protoc_insertion_point(module_scope)
