# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.check_response_serving_status import CheckResponseServingStatus
from openapi_server import util


class V1CheckResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status: CheckResponseServingStatus=None):
        """V1CheckResponse - a model defined in OpenAPI

        :param status: The status of this V1CheckResponse.
        """
        self.openapi_types = {
            'status': CheckResponseServingStatus
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt: dict) -> 'V1CheckResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The v1CheckResponse of this V1CheckResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this V1CheckResponse.


        :return: The status of this V1CheckResponse.
        :rtype: CheckResponseServingStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V1CheckResponse.


        :param status: The status of this V1CheckResponse.
        :type status: CheckResponseServingStatus
        """

        self._status = status
