# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util


class V1ExampleServiceQueryRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None):
        """V1ExampleServiceQueryRequest - a model defined in OpenAPI

        :param id: The id of this V1ExampleServiceQueryRequest.
        """
        self.openapi_types = {
            'id': str
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'V1ExampleServiceQueryRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The v1ExampleServiceQueryRequest of this V1ExampleServiceQueryRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this V1ExampleServiceQueryRequest.


        :return: The id of this V1ExampleServiceQueryRequest.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V1ExampleServiceQueryRequest.


        :param id: The id of this V1ExampleServiceQueryRequest.
        :type id: str
        """
        if id is not None and len(id) < 1:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")
        if id is not None and not re.search(r'[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}', id):
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}/`")

        self._id = id
