# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.protov1_status import Protov1Status
from openapi_server import util


class V1ExampleServiceQueryResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status: Protov1Status=None):
        """V1ExampleServiceQueryResponse - a model defined in OpenAPI

        :param status: The status of this V1ExampleServiceQueryResponse.
        """
        self.openapi_types = {
            'status': Protov1Status
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt: dict) -> 'V1ExampleServiceQueryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The v1ExampleServiceQueryResponse of this V1ExampleServiceQueryResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this V1ExampleServiceQueryResponse.


        :return: The status of this V1ExampleServiceQueryResponse.
        :rtype: Protov1Status
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V1ExampleServiceQueryResponse.


        :param status: The status of this V1ExampleServiceQueryResponse.
        :type status: Protov1Status
        """

        self._status = status
