# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.health_check_response_serving_status import HealthCheckResponseServingStatus
from openapi_server import util


class V1HealthCheckResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status: HealthCheckResponseServingStatus=None):
        """V1HealthCheckResponse - a model defined in OpenAPI

        :param status: The status of this V1HealthCheckResponse.
        """
        self.openapi_types = {
            'status': HealthCheckResponseServingStatus
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt: dict) -> 'V1HealthCheckResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The v1HealthCheckResponse of this V1HealthCheckResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this V1HealthCheckResponse.


        :return: The status of this V1HealthCheckResponse.
        :rtype: HealthCheckResponseServingStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V1HealthCheckResponse.


        :param status: The status of this V1HealthCheckResponse.
        :type status: HealthCheckResponseServingStatus
        """

        self._status = status
