# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CheckResponseServingStatus(str, Enum):
    """
    CheckResponseServingStatus
    """

    """
    allowed enum values
    """
    SERVING_STATUS_UNKNOWN_UNSPECIFIED = 'SERVING_STATUS_UNKNOWN_UNSPECIFIED'
    SERVING_STATUS_SERVING = 'SERVING_STATUS_SERVING'
    SERVING_STATUS_NOT_SERVING = 'SERVING_STATUS_NOT_SERVING'

    @classmethod
    def from_json(cls, json_str: str) -> CheckResponseServingStatus:
        """Create an instance of CheckResponseServingStatus from a JSON string"""
        return CheckResponseServingStatus(json.loads(json_str))


