# coding: utf-8

"""
    An example of generating swagger via gRPC ecosystem.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: none@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class HealthCheckResponseServingStatus(str, Enum):
    """
    HealthCheckResponseServingStatus
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    SERVING = 'SERVING'
    NOT_SERVING = 'NOT_SERVING'
    SERVICE_UNKNOWN = 'SERVICE_UNKNOWN'

    @classmethod
    def from_json(cls, json_str: str) -> HealthCheckResponseServingStatus:
        """Create an instance of HealthCheckResponseServingStatus from a JSON string"""
        return HealthCheckResponseServingStatus(json.loads(json_str))


