/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type HealthAPI struct {
	// Get /healthCheck
	//
	HealthCheck gin.HandlerFunc
	// Get /healthWatch
	//
	HealthWatch gin.HandlerFunc
}
