/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// V1CheckResponse - The response message containing the health status of the service.
type V1CheckResponse struct {
	Status V1ServingStatus `json:"status"`
}
