/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RpcCode string

// List of RpcCode
const (
	OK                  RpcCode = "OK"
	CANCELLED           RpcCode = "CANCELLED"
	UNKNOWN             RpcCode = "UNKNOWN"
	INVALID_ARGUMENT    RpcCode = "INVALID_ARGUMENT"
	DEADLINE_EXCEEDED   RpcCode = "DEADLINE_EXCEEDED"
	NOT_FOUND           RpcCode = "NOT_FOUND"
	ALREADY_EXISTS      RpcCode = "ALREADY_EXISTS"
	PERMISSION_DENIED   RpcCode = "PERMISSION_DENIED"
	UNAUTHENTICATED     RpcCode = "UNAUTHENTICATED"
	RESOURCE_EXHAUSTED  RpcCode = "RESOURCE_EXHAUSTED"
	FAILED_PRECONDITION RpcCode = "FAILED_PRECONDITION"
	ABORTED             RpcCode = "ABORTED"
	OUT_OF_RANGE        RpcCode = "OUT_OF_RANGE"
	UNIMPLEMENTED       RpcCode = "UNIMPLEMENTED"
	INTERNAL            RpcCode = "INTERNAL"
	UNAVAILABLE         RpcCode = "UNAVAILABLE"
	DATA_LOSS           RpcCode = "DATA_LOSS"
)
