# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.openapi_server.models.base_model import Model
from openapi_server import util


class CheckResponseServingStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NUMBER_&#39;SERVING_STATUS_UNKNOWN_UNSPECIFIED&#39; = 'SERVING_STATUS_UNKNOWN_UNSPECIFIED'
    NUMBER_&#39;SERVING_STATUS_SERVING&#39; = 'SERVING_STATUS_SERVING'
    NUMBER_&#39;SERVING_STATUS_NOT_SERVING&#39; = 'SERVING_STATUS_NOT_SERVING'

    def __init__(self):  # noqa: E501
        """CheckResponseServingStatus - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CheckResponseServingStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CheckResponseServingStatus of this CheckResponseServingStatus.  # noqa: E501
        :rtype: CheckResponseServingStatus
        """
        return util.deserialize_model(dikt, cls)
