# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.openapi_server.models.base_model_ import Model
from app.openapi_server.models.rpc_code import RpcCode  # noqa: F401,E501
from openapi_server import util


class ProtoResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: RpcCode=None, message: str=None):  # noqa: E501
        """ProtoResponse - a model defined in Swagger

        :param code: The code of this ProtoResponse.  # noqa: E501
        :type code: RpcCode
        :param message: The message of this ProtoResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'code': RpcCode,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ProtoResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The protoResponse of this ProtoResponse.  # noqa: E501
        :rtype: ProtoResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> RpcCode:
        """Gets the code of this ProtoResponse.


        :return: The code of this ProtoResponse.
        :rtype: RpcCode
        """
        return self._code

    @code.setter
    def code(self, code: RpcCode):
        """Sets the code of this ProtoResponse.


        :param code: The code of this ProtoResponse.
        :type code: RpcCode
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ProtoResponse.


        :return: The message of this ProtoResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ProtoResponse.


        :param message: The message of this ProtoResponse.
        :type message: str
        """

        self._message = message
