# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.openapi_server.models.base_model import Model
from app.openapi_server.models.check_response_serving_status import CheckResponseServingStatus  # noqa: F401,E501
from openapi_server import util


class V1CheckResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: CheckResponseServingStatus=None):  # noqa: E501
        """V1CheckResponse - a model defined in Swagger

        :param status: The status of this V1CheckResponse.  # noqa: E501
        :type status: CheckResponseServingStatus
        """
        self.swagger_types = {
            'status': CheckResponseServingStatus
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'V1CheckResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1CheckResponse of this V1CheckResponse.  # noqa: E501
        :rtype: V1CheckResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> CheckResponseServingStatus:
        """Gets the status of this V1CheckResponse.


        :return: The status of this V1CheckResponse.
        :rtype: CheckResponseServingStatus
        """
        return self._status

    @status.setter
    def status(self, status: CheckResponseServingStatus):
        """Sets the status of this V1CheckResponse.


        :param status: The status of this V1CheckResponse.
        :type status: CheckResponseServingStatus
        """

        self._status = status
