# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.openapi_server.models.base_model import Model
from app.openapi_server.models.health_check_response_serving_status import HealthCheckResponseServingStatus  # noqa: F401,E501
from openapi_server import util


class V1HealthCheckResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: HealthCheckResponseServingStatus=None):  # noqa: E501
        """V1HealthCheckResponse - a model defined in Swagger

        :param status: The status of this V1HealthCheckResponse.  # noqa: E501
        :type status: HealthCheckResponseServingStatus
        """
        self.swagger_types = {
            'status': HealthCheckResponseServingStatus
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'V1HealthCheckResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1HealthCheckResponse of this V1HealthCheckResponse.  # noqa: E501
        :rtype: V1HealthCheckResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> HealthCheckResponseServingStatus:
        """Gets the status of this V1HealthCheckResponse.


        :return: The status of this V1HealthCheckResponse.
        :rtype: HealthCheckResponseServingStatus
        """
        return self._status

    @status.setter
    def status(self, status: HealthCheckResponseServingStatus):
        """Sets the status of this V1HealthCheckResponse.


        :param status: The status of this V1HealthCheckResponse.
        :type status: HealthCheckResponseServingStatus
        """

        self._status = status
