// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/v1/helthcheck.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/emptypb"
	google_golang_org_protobuf_types_known_emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type HealthCheckServiceGQLServer struct{ Service HealthCheckServiceServer }

func (s *HealthCheckServiceGQLServer) HealthCheckServiceHealthCheck(ctx context.Context) (*HealthCheckServiceHealthCheckResponse, error) {
	return s.Service.HealthCheck(ctx, &google_golang_org_protobuf_types_known_emptypb.Empty{})
}
