// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/v1/service.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ExampleServiceGQLServer struct{ Service ExampleServiceServer }

func (s *ExampleServiceGQLServer) ExampleServiceQuery(ctx context.Context, in *ExampleServiceQueryRequest) (*ExampleServiceQueryResponse, error) {
	return s.Service.Query(ctx, in)
}
