// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ExampleServiceQuery implements ExampleService_Query operation.
//
// POST /v1/example/{id}
func (UnimplementedHandler) ExampleServiceQuery(ctx context.Context, req *ExampleServiceQueryBody, params ExampleServiceQueryParams) (r *V1ExampleServiceQueryResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthServiceCheck implements HealthService_Check operation.
//
// GET /v1/healthCheck
func (UnimplementedHandler) HealthServiceCheck(ctx context.Context, params HealthServiceCheckParams) (r *V1CheckResponse, _ error) {
	return r, ht.ErrNotImplemented
}
