// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// ExampleServiceQueryParams is parameters of ExampleService_Query operation.
type ExampleServiceQueryParams struct {
	ID uuid.UUID
}

func unpackExampleServiceQueryParams(packed middleware.Parameters) (params ExampleServiceQueryParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeExampleServiceQueryParams(args [1]string, argsEscaped bool, r *http.Request) (params ExampleServiceQueryParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// HealthServiceCheckParams is parameters of HealthService_Check operation.
type HealthServiceCheckParams struct {
	// The serving name as specified.
	ServingName string
}

func unpackHealthServiceCheckParams(packed middleware.Parameters) (params HealthServiceCheckParams) {
	{
		key := middleware.ParameterKey{
			Name: "servingName",
			In:   "query",
		}
		params.ServingName = packed[key].(string)
	}
	return params
}

func decodeHealthServiceCheckParams(args [0]string, argsEscaped bool, r *http.Request) (params HealthServiceCheckParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: servingName.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "servingName",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ServingName = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^proto$"],
				}).Validate(string(params.ServingName)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "servingName",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
