// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ExampleServiceQuery implements ExampleService_Query operation.
	//
	// POST /v1/example/{id}
	ExampleServiceQuery(ctx context.Context, req *ExampleServiceQueryBody, params ExampleServiceQueryParams) (*V1ExampleServiceQueryResponse, error)
	// HealthServiceCheck implements HealthService_Check operation.
	//
	// GET /v1/healthCheck
	HealthServiceCheck(ctx context.Context, params HealthServiceCheckParams) (*V1CheckResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
