// Code generated by ogen, DO NOT EDIT.

package oas

// setDefaults set default value of fields.
func (s *Protov1Status) setDefaults() {
	{
		val := RpcCode("OK")
		s.Code.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1CheckResponse) setDefaults() {
	{
		val := CheckResponseServingStatus("SERVING_STATUS_UNKNOWN_UNSPECIFIED")
		s.Status = val
	}
}
