/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// HealthAPIService is a service that implements the logic for the HealthAPIServicer
// This service should implement the business logic for every endpoint for the HealthAPI API.
// Include any external packages or services that will be required by this service.
type HealthAPIService struct {
}

// NewHealthAPIService creates a default api service
func NewHealthAPIService() HealthAPIServicer {
	return &HealthAPIService{}
}

// HealthCheck -
func (s *HealthAPIService) HealthCheck(ctx context.Context, service string) (ImplResponse, error) {
	// TODO - update HealthCheck with the required logic for this service method.
	// Add api_health_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, V1HealthCheckResponse{}) or use other options such as http.Ok ...
	// return Response(200, V1HealthCheckResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, RpcStatus{}) or use other options such as http.Ok ...
	// return Response(0, RpcStatus{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("HealthCheck method not implemented")
}

// HealthWatch -
func (s *HealthAPIService) HealthWatch(ctx context.Context, service string) (ImplResponse, error) {
	// TODO - update HealthWatch with the required logic for this service method.
	// Add api_health_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, StreamResultOfV1HealthCheckResponse{}) or use other options such as http.Ok ...
	// return Response(200, StreamResultOfV1HealthCheckResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, RpcStatus{}) or use other options such as http.Ok ...
	// return Response(0, RpcStatus{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("HealthWatch method not implemented")
}
