/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// HealthServiceAPIService is a service that implements the logic for the HealthServiceAPIServicer
// This service should implement the business logic for every endpoint for the HealthServiceAPI API.
// Include any external packages or services that will be required by this service.
type HealthServiceAPIService struct {
}

// NewHealthServiceAPIService creates a default api service
func NewHealthServiceAPIService() HealthServiceAPIServicer {
	return &HealthServiceAPIService{}
}

// HealthServiceCheck -
func (s *HealthServiceAPIService) HealthServiceCheck(ctx context.Context, service string) (ImplResponse, error) {
	// TODO - update HealthServiceCheck with the required logic for this service method.
	// Add api_health_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, V1CheckResponse{}) or use other options such as http.Ok ...
	// return Response(200, V1CheckResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, RpcStatus{}) or use other options such as http.Ok ...
	// return Response(0, RpcStatus{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("HealthServiceCheck method not implemented")
}
