/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// HealthCheckServiceApiService is a service that implements the logic for the HealthCheckServiceApiServicer
// This service should implement the business logic for every endpoint for the HealthCheckServiceApi API.
// Include any external packages or services that will be required by this service.
type HealthCheckServiceApiService struct {
}

// NewHealthCheckServiceApiService creates a default api service
func NewHealthCheckServiceApiService() HealthCheckServiceApiServicer {
	return &HealthCheckServiceApiService{}
}

// HealthCheck -
func (s *HealthCheckServiceApiService) HealthCheck(ctx context.Context) (ImplResponse, error) {
	// TODO - update HealthCheck with the required logic for this service method.
	// Add api_health_check_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, V1HealthCheckServiceHealthCheckResponse{}) or use other options such as http.Ok ...
	//return Response(200, V1HealthCheckServiceHealthCheckResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("HealthCheck method not implemented")
}
