/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// ExampleServiceApiController binds http requests to an api service and writes the service results to the http response
type ExampleServiceApiController struct {
	service      ExampleServiceApiServicer
	errorHandler ErrorHandler
}

// ExampleServiceApiOption for how the controller is set up.
type ExampleServiceApiOption func(*ExampleServiceApiController)

// WithExampleServiceApiErrorHandler inject ErrorHandler into controller
func WithExampleServiceApiErrorHandler(h ErrorHandler) ExampleServiceApiOption {
	return func(c *ExampleServiceApiController) {
		c.errorHandler = h
	}
}

// NewExampleServiceApiController creates a default api controller
func NewExampleServiceApiController(s ExampleServiceApiServicer, opts ...ExampleServiceApiOption) Router {
	controller := &ExampleServiceApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ExampleServiceApiController
func (c *ExampleServiceApiController) Routes() Routes {
	return Routes{
		{
			"Query",
			strings.ToUpper("Post"),
			"/v1/example/{id}",
			c.Query,
		},
	}
}

// Query -
func (c *ExampleServiceApiController) Query(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]

	bodyParam := V1ExampleServiceQueryRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertV1ExampleServiceQueryRequestRequired(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Query(r.Context(), idParam, bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
