/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// HealthCheckServiceAPIController binds http requests to an api service and writes the service results to the http response
type HealthCheckServiceAPIController struct {
	service      HealthCheckServiceAPIServicer
	errorHandler ErrorHandler
}

// HealthCheckServiceAPIOption for how the controller is set up.
type HealthCheckServiceAPIOption func(*HealthCheckServiceAPIController)

// WithHealthCheckServiceAPIErrorHandler inject ErrorHandler into controller
func WithHealthCheckServiceAPIErrorHandler(h ErrorHandler) HealthCheckServiceAPIOption {
	return func(c *HealthCheckServiceAPIController) {
		c.errorHandler = h
	}
}

// NewHealthCheckServiceAPIController creates a default api controller
func NewHealthCheckServiceAPIController(s HealthCheckServiceAPIServicer, opts ...HealthCheckServiceAPIOption) Router {
	controller := &HealthCheckServiceAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the HealthCheckServiceAPIController
func (c *HealthCheckServiceAPIController) Routes() Routes {
	return Routes{
		"HealthCheck": Route{
			strings.ToUpper("Get"),
			"/healthCheck",
			c.HealthCheck,
		},
	}
}

// HealthCheck -
func (c *HealthCheckServiceAPIController) HealthCheck(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.HealthCheck(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
