/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProtobufAny struct {
	Type string `json:"@type,omitempty"`
}

// AssertProtobufAnyRequired checks if the required fields are not zero-ed
func AssertProtobufAnyRequired(obj ProtobufAny) error {
	return nil
}

// AssertProtobufAnyConstraints checks if the values respects the defined constraints
func AssertProtobufAnyConstraints(obj ProtobufAny) error {
	return nil
}
