/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1ExampleServiceQueryResponse struct {
	Value Protov1Response `json:"value,omitempty"`
}

// AssertV1ExampleServiceQueryResponseRequired checks if the required fields are not zero-ed
func AssertV1ExampleServiceQueryResponseRequired(obj V1ExampleServiceQueryResponse) error {
	if err := AssertProtov1ResponseRequired(obj.Value); err != nil {
		return err
	}
	return nil
}

// AssertV1ExampleServiceQueryResponseConstraints checks if the values respects the defined constraints
func AssertV1ExampleServiceQueryResponseConstraints(obj V1ExampleServiceQueryResponse) error {
	return nil
}
