/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RpcStatus struct {
	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Details []ProtobufAny `json:"details,omitempty"`
}

// AssertRpcStatusRequired checks if the required fields are not zero-ed
func AssertRpcStatusRequired(obj RpcStatus) error {
	return nil
}

// AssertRpcStatusConstraints checks if the values respects the defined constraints
func AssertRpcStatusConstraints(obj RpcStatus) error {
	return nil
}
