/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1ExampleServiceQueryResponse struct {
	Value Protov1Response `json:"value,omitempty"`
}

// AssertV1ExampleServiceQueryResponseRequired checks if the required fields are not zero-ed
func AssertV1ExampleServiceQueryResponseRequired(obj V1ExampleServiceQueryResponse) error {
	if err := AssertProtov1ResponseRequired(obj.Value); err != nil {
		return err
	}
	return nil
}

// AssertRecurseV1ExampleServiceQueryResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of V1ExampleServiceQueryResponse (e.g. [][]V1ExampleServiceQueryResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseV1ExampleServiceQueryResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aV1ExampleServiceQueryResponse, ok := obj.(V1ExampleServiceQueryResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertV1ExampleServiceQueryResponseRequired(aV1ExampleServiceQueryResponse)
	})
}
