// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 */

package openapi

import (
	"fmt"
)

type V1ServingStatus string

// List of V1ServingStatus
const (
	SERVING_STATUS_UNKNOWN_UNSPECIFIED V1ServingStatus = "SERVING_STATUS_UNKNOWN_UNSPECIFIED"
	SERVING_STATUS_SERVING             V1ServingStatus = "SERVING_STATUS_SERVING"
	SERVING_STATUS_NOT_SERVING         V1ServingStatus = "SERVING_STATUS_NOT_SERVING"
)

// AllowedV1ServingStatusEnumValues is all the allowed values of V1ServingStatus enum
var AllowedV1ServingStatusEnumValues = []V1ServingStatus{
	"SERVING_STATUS_UNKNOWN_UNSPECIFIED",
	"SERVING_STATUS_SERVING",
	"SERVING_STATUS_NOT_SERVING",
}

// validV1ServingStatusEnumValue provides a map of V1ServingStatuss for fast verification of use input
var validV1ServingStatusEnumValues = map[V1ServingStatus]struct{}{
	"SERVING_STATUS_UNKNOWN_UNSPECIFIED": {},
	"SERVING_STATUS_SERVING":             {},
	"SERVING_STATUS_NOT_SERVING":         {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1ServingStatus) IsValid() bool {
	_, ok := validV1ServingStatusEnumValues[v]
	return ok
}

// NewV1ServingStatusFromValue returns a pointer to a valid V1ServingStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1ServingStatusFromValue(v string) (V1ServingStatus, error) {
	ev := V1ServingStatus(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for V1ServingStatus: valid values are %v", v, AllowedV1ServingStatusEnumValues)
}

// AssertV1ServingStatusRequired checks if the required fields are not zero-ed
func AssertV1ServingStatusRequired(obj V1ServingStatus) error {
	return nil
}

// AssertV1ServingStatusConstraints checks if the values respects the defined constraints
func AssertV1ServingStatusConstraints(obj V1ServingStatus) error {
	return nil
}
