/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1HealthCheckServiceHealthCheckResponse struct {
	Value Protov1Response `json:"value,omitempty"`
}

// AssertV1HealthCheckServiceHealthCheckResponseRequired checks if the required fields are not zero-ed
func AssertV1HealthCheckServiceHealthCheckResponseRequired(obj V1HealthCheckServiceHealthCheckResponse) error {
	if err := AssertProtov1ResponseRequired(obj.Value); err != nil {
		return err
	}
	return nil
}

// AssertRecurseV1HealthCheckServiceHealthCheckResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of V1HealthCheckServiceHealthCheckResponse (e.g. [][]V1HealthCheckServiceHealthCheckResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseV1HealthCheckServiceHealthCheckResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aV1HealthCheckServiceHealthCheckResponse, ok := obj.(V1HealthCheckServiceHealthCheckResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertV1HealthCheckServiceHealthCheckResponseRequired(aV1HealthCheckServiceHealthCheckResponse)
	})
}
