/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type HealthCheckResponseServingStatus string

// List of HealthCheckResponseServingStatus
const (
	UNKNOWN         HealthCheckResponseServingStatus = "UNKNOWN"
	SERVING         HealthCheckResponseServingStatus = "SERVING"
	NOT_SERVING     HealthCheckResponseServingStatus = "NOT_SERVING"
	SERVICE_UNKNOWN HealthCheckResponseServingStatus = "SERVICE_UNKNOWN"
)

// AssertHealthCheckResponseServingStatusRequired checks if the required fields are not zero-ed
func AssertHealthCheckResponseServingStatusRequired(obj HealthCheckResponseServingStatus) error {
	return nil
}

// AssertHealthCheckResponseServingStatusConstraints checks if the values respects the defined constraints
func AssertHealthCheckResponseServingStatusConstraints(obj HealthCheckResponseServingStatus) error {
	return nil
}
