// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 */

package openapi

// V1CheckResponse - The response message containing the health status of the service.
type V1CheckResponse struct {
	Status V1ServingStatus `json:"status"`
}

// AssertV1CheckResponseRequired checks if the required fields are not zero-ed
func AssertV1CheckResponseRequired(obj V1CheckResponse) error {
	elements := map[string]interface{}{
		"status": obj.Status,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertV1CheckResponseConstraints checks if the values respects the defined constraints
func AssertV1CheckResponseConstraints(obj V1CheckResponse) error {
	return nil
}
