/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1HealthCheckResponse struct {
	Status HealthCheckResponseServingStatus `json:"status,omitempty"`
}

// AssertV1HealthCheckResponseRequired checks if the required fields are not zero-ed
func AssertV1HealthCheckResponseRequired(obj V1HealthCheckResponse) error {
	return nil
}

// AssertV1HealthCheckResponseConstraints checks if the values respects the defined constraints
func AssertV1HealthCheckResponseConstraints(obj V1HealthCheckResponse) error {
	return nil
}
