/*
 * check_response_serving_status.h
 *
 * 
 */

#ifndef _check_response_serving_status_H_
#define _check_response_serving_status_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct check_response_serving_status_t check_response_serving_status_t;


// Enum  for check_response_serving_status

typedef enum { an_example_of_generating_swagger_via_grpc_ecosystem__check_response_serving_status__NULL = 0, an_example_of_generating_swagger_via_grpc_ecosystem__check_response_serving_status__SERVING_STATUS_UNKNOWN_UNSPECIFIED, an_example_of_generating_swagger_via_grpc_ecosystem__check_response_serving_status__SERVING_STATUS_SERVING, an_example_of_generating_swagger_via_grpc_ecosystem__check_response_serving_status__SERVING_STATUS_NOT_SERVING } an_example_of_generating_swagger_via_grpc_ecosystem__check_response_serving_status__e;

char* check_response_serving_status_check_response_serving_status_ToString(an_example_of_generating_swagger_via_grpc_ecosystem__check_response_serving_status__e check_response_serving_status);

an_example_of_generating_swagger_via_grpc_ecosystem__check_response_serving_status__e check_response_serving_status_check_response_serving_status_FromString(char* check_response_serving_status);

//cJSON *check_response_serving_status_check_response_serving_status_convertToJSON(an_example_of_generating_swagger_via_grpc_ecosystem__check_response_serving_status__e check_response_serving_status);

//an_example_of_generating_swagger_via_grpc_ecosystem__check_response_serving_status__e check_response_serving_status_check_response_serving_status_parseFromJSON(cJSON *check_response_serving_statusJSON);

#endif /* _check_response_serving_status_H_ */

