/*
 * health_check_response_serving_status.h
 *
 * 
 */

#ifndef _health_check_response_serving_status_H_
#define _health_check_response_serving_status_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct health_check_response_serving_status_t health_check_response_serving_status_t;


// Enum  for health_check_response_serving_status

typedef enum { an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__NULL = 0, an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__UNKNOWN, an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__SERVING, an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__NOT_SERVING, an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__SERVICE_UNKNOWN } an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__e;

char* health_check_response_serving_status_health_check_response_serving_status_ToString(an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__e health_check_response_serving_status);

an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__e health_check_response_serving_status_health_check_response_serving_status_FromString(char* health_check_response_serving_status);

//cJSON *health_check_response_serving_status_health_check_response_serving_status_convertToJSON(an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__e health_check_response_serving_status);

//an_example_of_generating_swagger_via_grpc_ecosystem__health_check_response_serving_status__e health_check_response_serving_status_health_check_response_serving_status_parseFromJSON(cJSON *health_check_response_serving_statusJSON);

#endif /* _health_check_response_serving_status_H_ */

