/*
 * proto_response.h
 *
 * 
 */

#ifndef _proto_response_H_
#define _proto_response_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct proto_response_t proto_response_t;

#include "rpc_code.h"

// Enum  for proto_response

typedef enum  { an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__NULL = 0, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__OK, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__CANCELLED, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__UNKNOWN, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__INVALID_ARGUMENT, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__DEADLINE_EXCEEDED, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__NOT_FOUND, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__ALREADY_EXISTS, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__PERMISSION_DENIED, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__UNAUTHENTICATED, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__RESOURCE_EXHAUSTED, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__FAILED_PRECONDITION, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__ABORTED, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__OUT_OF_RANGE, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__UNIMPLEMENTED, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__INTERNAL, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__UNAVAILABLE, an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__DATA_LOSS } an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__e;

char* proto_response_code_ToString(an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__e code);

an_example_of_generating_swagger_via_grpc_ecosystem__proto_response__e proto_response_code_FromString(char* code);



typedef struct proto_response_t {
    char *message; // string

} proto_response_t;

proto_response_t *proto_response_create(
    char *message
);

void proto_response_free(proto_response_t *proto_response);

proto_response_t *proto_response_parseFromJSON(cJSON *proto_responseJSON);

cJSON *proto_response_convertToJSON(proto_response_t *proto_response);

#endif /* _proto_response_H_ */

