=begin
#proto/helthcheck.proto

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: version not set

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.3-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::HealthCheckApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HealthCheckApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::HealthCheckApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HealthCheckApi' do
    it 'should create an instance of HealthCheckApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::HealthCheckApi)
    end
  end

  # unit tests for get
  # @param [Hash] opts the optional parameters
  # @return [GatewayHealthCheckResponse]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
