=begin
#An example of generating swagger via gRPC ecosystem.

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Contact: none@example.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::HealthCheckServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HealthCheckServiceApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::HealthCheckServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HealthCheckServiceApi' do
    it 'should create an instance of HealthCheckServiceApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::HealthCheckServiceApi)
    end
  end

  # unit tests for health_check_service_health_check
  # @param [Hash] opts the optional parameters
  # @return [V1HealthCheckServiceHealthCheckResponse]
  describe 'health_check_service_health_check test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
