/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	ExampleServiceApiService := openapi.NewExampleServiceApiService()
	ExampleServiceApiController := openapi.NewExampleServiceApiController(ExampleServiceApiService)

	HealthCheckServiceApiService := openapi.NewHealthCheckServiceApiService()
	HealthCheckServiceApiController := openapi.NewHealthCheckServiceApiController(HealthCheckServiceApiService)

	router := openapi.NewRouter(ExampleServiceApiController, HealthCheckServiceApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
