/* tslint:disable */
/* eslint-disable */
/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    RuntimeError,
    RuntimeErrorFromJSON,
    RuntimeErrorToJSON,
    V1ExampleServiceQueryRequest,
    V1ExampleServiceQueryRequestFromJSON,
    V1ExampleServiceQueryRequestToJSON,
    V1ExampleServiceQueryResponse,
    V1ExampleServiceQueryResponseFromJSON,
    V1ExampleServiceQueryResponseToJSON,
} from '../models';

export interface ExampleServiceQueryRequest {
    id: string;
    body: V1ExampleServiceQueryRequest;
}

/**
 * 
 */
export class ExampleServiceApi extends runtime.BaseAPI {

    /**
     */
    async exampleServiceQueryRaw(requestParameters: ExampleServiceQueryRequest): Promise<runtime.ApiResponse<V1ExampleServiceQueryResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling exampleServiceQuery.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling exampleServiceQuery.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("OAuth2", ["read", "write"]);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/v1/example/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1ExampleServiceQueryRequestToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => V1ExampleServiceQueryResponseFromJSON(jsonValue));
    }

    /**
     */
    async exampleServiceQuery(requestParameters: ExampleServiceQueryRequest): Promise<V1ExampleServiceQueryResponse> {
        const response = await this.exampleServiceQueryRaw(requestParameters);
        return await response.value();
    }

}
