/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CheckResponseServingStatus = 'SERVING_STATUS_UNKNOWN_UNSPECIFIED' | 'SERVING_STATUS_SERVING' | 'SERVING_STATUS_NOT_SERVING';

export const CheckResponseServingStatus = {
    UnknownUnspecified: 'SERVING_STATUS_UNKNOWN_UNSPECIFIED' as CheckResponseServingStatus,
    Serving: 'SERVING_STATUS_SERVING' as CheckResponseServingStatus,
    NotServing: 'SERVING_STATUS_NOT_SERVING' as CheckResponseServingStatus
};

