/**
 * An example of generating swagger via gRPC ecosystem.
 *
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RpcCode } from './rpcCode';


export interface Protov1Status { 
    /**
     * The \"type\" member is a JSON string containing a URI reference [URI] that identifies the problem/response type. Consumers MUST use the \"type\" URI (after resolution, if necessary) as the problem/response type\'s primary identifier. When this member is not present, its value is assumed to be \"about:blank\".
     */
    type?: string;
    /**
     * The \"status\" member is a JSON number indicating the HTTP status code ([HTTP], Section 15) generated by the origin server for this occurrence of the problem/response. The HTTP status code that corresponds to `google.rpc.Status.code`.
     */
    status?: number;
    /**
     * The \"title\" member is a JSON string containing a short, human-readable summary of the problem/response type.
     */
    title?: string;
    /**
     * The \"detail\" member is a JSON string containing a human-readable explanation specific to this occurrence of the problem/response. The \"detail\" string, if present, ought to focus on helping the client correct the problem/response, rather than giving debugging information.
     */
    detail?: string;
    /**
     * The \"instance\" member is a JSON string containing a URI reference that identifies the specific occurrence of the problem/response.
     */
    instance?: string;
    /**
     * Problem type definitions MAY extend the problem details object with additional members that are specific to that problem type.
     */
    extensions?: Array<string>;
    code?: RpcCode;
}
export namespace Protov1Status {
}


