/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RpcCode = 'OK' | 'CANCELLED' | 'UNKNOWN' | 'INVALID_ARGUMENT' | 'DEADLINE_EXCEEDED' | 'NOT_FOUND' | 'ALREADY_EXISTS' | 'PERMISSION_DENIED' | 'UNAUTHENTICATED' | 'RESOURCE_EXHAUSTED' | 'FAILED_PRECONDITION' | 'ABORTED' | 'OUT_OF_RANGE' | 'UNIMPLEMENTED' | 'INTERNAL' | 'UNAVAILABLE' | 'DATA_LOSS';

export const RpcCode = {
    Ok: 'OK' as RpcCode,
    Cancelled: 'CANCELLED' as RpcCode,
    Unknown: 'UNKNOWN' as RpcCode,
    InvalidArgument: 'INVALID_ARGUMENT' as RpcCode,
    DeadlineExceeded: 'DEADLINE_EXCEEDED' as RpcCode,
    NotFound: 'NOT_FOUND' as RpcCode,
    AlreadyExists: 'ALREADY_EXISTS' as RpcCode,
    PermissionDenied: 'PERMISSION_DENIED' as RpcCode,
    Unauthenticated: 'UNAUTHENTICATED' as RpcCode,
    ResourceExhausted: 'RESOURCE_EXHAUSTED' as RpcCode,
    FailedPrecondition: 'FAILED_PRECONDITION' as RpcCode,
    Aborted: 'ABORTED' as RpcCode,
    OutOfRange: 'OUT_OF_RANGE' as RpcCode,
    Unimplemented: 'UNIMPLEMENTED' as RpcCode,
    Internal: 'INTERNAL' as RpcCode,
    Unavailable: 'UNAVAILABLE' as RpcCode,
    DataLoss: 'DATA_LOSS' as RpcCode
};

