/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CheckResponseServingStatus } from './checkResponseServingStatus';


/**
 * The response message containing the health status of the service.
 */
export interface V1CheckResponse { 
    status: CheckResponseServingStatus;
}
export namespace V1CheckResponse {
}


