/**
 * An example of generating swagger via gRPC ecosystem.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HealthCheckResponseServingStatus } from './healthCheckResponseServingStatus';


export interface V1HealthCheckResponse { 
    status?: HealthCheckResponseServingStatus;
}
export namespace V1HealthCheckResponse {
}


