/**
 * An example of generating swagger via gRPC ecosystem.
 *
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const V1ServingStatus = {
    ServingStatusUnknownUnspecified: 'SERVING_STATUS_UNKNOWN_UNSPECIFIED',
    ServingStatusServing: 'SERVING_STATUS_SERVING',
    ServingStatusNotServing: 'SERVING_STATUS_NOT_SERVING'
} as const;
export type V1ServingStatus = typeof V1ServingStatus[keyof typeof V1ServingStatus];

