/*
An example of generating swagger via gRPC ecosystem.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
Contact: none@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V1HealthCheckServiceHealthCheckResponse struct for V1HealthCheckServiceHealthCheckResponse
type V1HealthCheckServiceHealthCheckResponse struct {
	Value *Protov1Response `json:"value,omitempty"`
}

// NewV1HealthCheckServiceHealthCheckResponse instantiates a new V1HealthCheckServiceHealthCheckResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1HealthCheckServiceHealthCheckResponse() *V1HealthCheckServiceHealthCheckResponse {
	this := V1HealthCheckServiceHealthCheckResponse{}
	return &this
}

// NewV1HealthCheckServiceHealthCheckResponseWithDefaults instantiates a new V1HealthCheckServiceHealthCheckResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1HealthCheckServiceHealthCheckResponseWithDefaults() *V1HealthCheckServiceHealthCheckResponse {
	this := V1HealthCheckServiceHealthCheckResponse{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *V1HealthCheckServiceHealthCheckResponse) GetValue() Protov1Response {
	if o == nil || o.Value == nil {
		var ret Protov1Response
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1HealthCheckServiceHealthCheckResponse) GetValueOk() (*Protov1Response, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *V1HealthCheckServiceHealthCheckResponse) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given Protov1Response and assigns it to the Value field.
func (o *V1HealthCheckServiceHealthCheckResponse) SetValue(v Protov1Response) {
	o.Value = &v
}

func (o V1HealthCheckServiceHealthCheckResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableV1HealthCheckServiceHealthCheckResponse struct {
	value *V1HealthCheckServiceHealthCheckResponse
	isSet bool
}

func (v NullableV1HealthCheckServiceHealthCheckResponse) Get() *V1HealthCheckServiceHealthCheckResponse {
	return v.value
}

func (v *NullableV1HealthCheckServiceHealthCheckResponse) Set(val *V1HealthCheckServiceHealthCheckResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1HealthCheckServiceHealthCheckResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1HealthCheckServiceHealthCheckResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1HealthCheckServiceHealthCheckResponse(val *V1HealthCheckServiceHealthCheckResponse) *NullableV1HealthCheckServiceHealthCheckResponse {
	return &NullableV1HealthCheckServiceHealthCheckResponse{value: val, isSet: true}
}

func (v NullableV1HealthCheckServiceHealthCheckResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1HealthCheckServiceHealthCheckResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


