/*
An example of generating swagger via gRPC ecosystem.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
Contact: none@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1ExampleServiceQueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExampleServiceQueryResponse{}

// V1ExampleServiceQueryResponse struct for V1ExampleServiceQueryResponse
type V1ExampleServiceQueryResponse struct {
	Value *Protov1Response `json:"value,omitempty"`
}

// NewV1ExampleServiceQueryResponse instantiates a new V1ExampleServiceQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExampleServiceQueryResponse() *V1ExampleServiceQueryResponse {
	this := V1ExampleServiceQueryResponse{}
	return &this
}

// NewV1ExampleServiceQueryResponseWithDefaults instantiates a new V1ExampleServiceQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExampleServiceQueryResponseWithDefaults() *V1ExampleServiceQueryResponse {
	this := V1ExampleServiceQueryResponse{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *V1ExampleServiceQueryResponse) GetValue() Protov1Response {
	if o == nil || IsNil(o.Value) {
		var ret Protov1Response
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExampleServiceQueryResponse) GetValueOk() (*Protov1Response, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *V1ExampleServiceQueryResponse) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given Protov1Response and assigns it to the Value field.
func (o *V1ExampleServiceQueryResponse) SetValue(v Protov1Response) {
	o.Value = &v
}

func (o V1ExampleServiceQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExampleServiceQueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableV1ExampleServiceQueryResponse struct {
	value *V1ExampleServiceQueryResponse
	isSet bool
}

func (v NullableV1ExampleServiceQueryResponse) Get() *V1ExampleServiceQueryResponse {
	return v.value
}

func (v *NullableV1ExampleServiceQueryResponse) Set(val *V1ExampleServiceQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExampleServiceQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExampleServiceQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExampleServiceQueryResponse(val *V1ExampleServiceQueryResponse) *NullableV1ExampleServiceQueryResponse {
	return &NullableV1ExampleServiceQueryResponse{value: val, isSet: true}
}

func (v NullableV1ExampleServiceQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExampleServiceQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
