/*
An example of generating swagger via gRPC ecosystem.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
Contact: none@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1CheckResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CheckResponse{}

// V1CheckResponse The response message containing the health status of the service.
type V1CheckResponse struct {
	Status CheckResponseServingStatus `json:"status"`
}

// NewV1CheckResponse instantiates a new V1CheckResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CheckResponse(status CheckResponseServingStatus) *V1CheckResponse {
	this := V1CheckResponse{}
	this.Status = status
	return &this
}

// NewV1CheckResponseWithDefaults instantiates a new V1CheckResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CheckResponseWithDefaults() *V1CheckResponse {
	this := V1CheckResponse{}
	var status CheckResponseServingStatus = UNKNOWN_UNSPECIFIED
	this.Status = status
	return &this
}

// GetStatus returns the Status field value
func (o *V1CheckResponse) GetStatus() CheckResponseServingStatus {
	if o == nil {
		var ret CheckResponseServingStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V1CheckResponse) GetStatusOk() (*CheckResponseServingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V1CheckResponse) SetStatus(v CheckResponseServingStatus) {
	o.Status = v
}

func (o V1CheckResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CheckResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

type NullableV1CheckResponse struct {
	value *V1CheckResponse
	isSet bool
}

func (v NullableV1CheckResponse) Get() *V1CheckResponse {
	return v.value
}

func (v *NullableV1CheckResponse) Set(val *V1CheckResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CheckResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CheckResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CheckResponse(val *V1CheckResponse) *NullableV1CheckResponse {
	return &NullableV1CheckResponse{value: val, isSet: true}
}

func (v NullableV1CheckResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CheckResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
