/*
An example of generating swagger via gRPC ecosystem.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
Contact: none@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V1ExampleServiceQueryRequest struct for V1ExampleServiceQueryRequest
type V1ExampleServiceQueryRequest struct {
	Id *string `json:"id,omitempty"`
}

// NewV1ExampleServiceQueryRequest instantiates a new V1ExampleServiceQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExampleServiceQueryRequest() *V1ExampleServiceQueryRequest {
	this := V1ExampleServiceQueryRequest{}
	return &this
}

// NewV1ExampleServiceQueryRequestWithDefaults instantiates a new V1ExampleServiceQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExampleServiceQueryRequestWithDefaults() *V1ExampleServiceQueryRequest {
	this := V1ExampleServiceQueryRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V1ExampleServiceQueryRequest) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExampleServiceQueryRequest) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V1ExampleServiceQueryRequest) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V1ExampleServiceQueryRequest) SetId(v string) {
	o.Id = &v
}

func (o V1ExampleServiceQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableV1ExampleServiceQueryRequest struct {
	value *V1ExampleServiceQueryRequest
	isSet bool
}

func (v NullableV1ExampleServiceQueryRequest) Get() *V1ExampleServiceQueryRequest {
	return v.value
}

func (v *NullableV1ExampleServiceQueryRequest) Set(val *V1ExampleServiceQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExampleServiceQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExampleServiceQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExampleServiceQueryRequest(val *V1ExampleServiceQueryRequest) *NullableV1ExampleServiceQueryRequest {
	return &NullableV1ExampleServiceQueryRequest{value: val, isSet: true}
}

func (v NullableV1ExampleServiceQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExampleServiceQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


