/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1HealthCheckServiceHealthCheckResponse struct for V1HealthCheckServiceHealthCheckResponse
type V1HealthCheckServiceHealthCheckResponse struct {
	Value Protov1Response `json:"value,omitempty"`
}
