/*
An example of generating swagger via gRPC ecosystem.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
Contact: none@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the V1CheckResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CheckResponse{}

// V1CheckResponse The response message containing the health status of the service.
type V1CheckResponse struct {
	Status V1ServingStatus `json:"status"`
}

type _V1CheckResponse V1CheckResponse

// NewV1CheckResponse instantiates a new V1CheckResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CheckResponse(status V1ServingStatus) *V1CheckResponse {
	this := V1CheckResponse{}
	this.Status = status
	return &this
}

// NewV1CheckResponseWithDefaults instantiates a new V1CheckResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CheckResponseWithDefaults() *V1CheckResponse {
	this := V1CheckResponse{}
	var status V1ServingStatus = SERVING_STATUS_UNKNOWN_UNSPECIFIED
	this.Status = status
	return &this
}

// GetStatus returns the Status field value
func (o *V1CheckResponse) GetStatus() V1ServingStatus {
	if o == nil {
		var ret V1ServingStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V1CheckResponse) GetStatusOk() (*V1ServingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V1CheckResponse) SetStatus(v V1ServingStatus) {
	o.Status = v
}

func (o V1CheckResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CheckResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *V1CheckResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1CheckResponse := _V1CheckResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1CheckResponse)

	if err != nil {
		return err
	}

	*o = V1CheckResponse(varV1CheckResponse)

	return err
}

type NullableV1CheckResponse struct {
	value *V1CheckResponse
	isSet bool
}

func (v NullableV1CheckResponse) Get() *V1CheckResponse {
	return v.value
}

func (v *NullableV1CheckResponse) Set(val *V1CheckResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CheckResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CheckResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CheckResponse(val *V1CheckResponse) *NullableV1CheckResponse {
	return &NullableV1CheckResponse{value: val, isSet: true}
}

func (v NullableV1CheckResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CheckResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
