# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helthcheck.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='helthcheck.proto',
  package='gateway',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10helthcheck.proto\x12\x07gateway\x1a\x1cgoogle/api/annotations.proto\"\x07\n\x05\x45mpty\"!\n\x13HealthCheckResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32X\n\x0bHealthCheck\x12I\n\x03Get\x12\x0e.gateway.Empty\x1a\x1c.gateway.HealthCheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/healthcheckb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='gateway.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=66,
)


_HEALTHCHECKRESPONSE = _descriptor.Descriptor(
  name='HealthCheckResponse',
  full_name='gateway.HealthCheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='gateway.HealthCheckResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['HealthCheckResponse'] = _HEALTHCHECKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'helthcheck_pb2'
  # @@protoc_insertion_point(class_scope:gateway.Empty)
  })
_sym_db.RegisterMessage(Empty)

HealthCheckResponse = _reflection.GeneratedProtocolMessageType('HealthCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKRESPONSE,
  '__module__' : 'helthcheck_pb2'
  # @@protoc_insertion_point(class_scope:gateway.HealthCheckResponse)
  })
_sym_db.RegisterMessage(HealthCheckResponse)



_HEALTHCHECK = _descriptor.ServiceDescriptor(
  name='HealthCheck',
  full_name='gateway.HealthCheck',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=103,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='gateway.HealthCheck.Get',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_HEALTHCHECKRESPONSE,
    serialized_options=_b('\202\323\344\223\002\016\022\014/healthcheck'),
  ),
])
_sym_db.RegisterServiceDescriptor(_HEALTHCHECK)

DESCRIPTOR.services_by_name['HealthCheck'] = _HEALTHCHECK

# @@protoc_insertion_point(module_scope)
