# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helthcheck_pb2 as helthcheck__pb2


class HealthCheckStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/gateway.HealthCheck/Get',
        request_serializer=helthcheck__pb2.Empty.SerializeToString,
        response_deserializer=helthcheck__pb2.HealthCheckResponse.FromString,
        )


class HealthCheckServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HealthCheckServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=helthcheck__pb2.Empty.FromString,
          response_serializer=helthcheck__pb2.HealthCheckResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gateway.HealthCheck', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
