//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openapi/api.dart';
import 'package:test/test.dart';

// tests for Protov1Status
void main() {
  // final instance = Protov1Status();

  group('test Protov1Status', () {
    // The \"type\" member is a JSON string containing a URI reference [URI] that identifies the problem/response type. Consumers MUST use the \"type\" URI (after resolution, if necessary) as the problem/response type's primary identifier. When this member is not present, its value is assumed to be \"about:blank\".
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The \"status\" member is a JSON number indicating the HTTP status code ([HTTP], Section 15) generated by the origin server for this occurrence of the problem/response. The HTTP status code that corresponds to `google.rpc.Status.code`.
    // int status
    test('to test the property `status`', () async {
      // TODO
    });

    // The \"title\" member is a JSON string containing a short, human-readable summary of the problem/response type.
    // String title
    test('to test the property `title`', () async {
      // TODO
    });

    // The \"detail\" member is a JSON string containing a human-readable explanation specific to this occurrence of the problem/response. The \"detail\" string, if present, ought to focus on helping the client correct the problem/response, rather than giving debugging information.
    // String detail
    test('to test the property `detail`', () async {
      // TODO
    });

    // The \"instance\" member is a JSON string containing a URI reference that identifies the specific occurrence of the problem/response.
    // String instance
    test('to test the property `instance`', () async {
      // TODO
    });

    // Problem type definitions MAY extend the problem details object with additional members that are specific to that problem type.
    // List<String> extensions (default value: const [])
    test('to test the property `extensions`', () async {
      // TODO
    });

    // RpcCode code
    test('to test the property `code`', () async {
      // TODO
    });


  });

}
