/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 * Generated by: https://openapi-generator.tech
 */

/// V1CheckResponse : The response message containing the health status of the service.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CheckResponse {
    #[serde(rename = "status")]
    pub status: crate::models::CheckResponseServingStatus,
}

impl V1CheckResponse {
    /// The response message containing the health status of the service.
    pub fn new(status: crate::models::CheckResponseServingStatus) -> V1CheckResponse {
        V1CheckResponse {
            status,
        }
    }
}


