/*
 * An example of generating swagger via gRPC ecosystem.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: none@example.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CheckResponse : The response message containing the health status of the service.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CheckResponse {
    #[serde(rename = "status")]
    pub status: models::V1ServingStatus,
}

impl V1CheckResponse {
    /// The response message containing the health status of the service.
    pub fn new(status: models::V1ServingStatus) -> V1CheckResponse {
        V1CheckResponse {
            status,
        }
    }
}

