# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/helthcheck.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import message_pb2 as proto_dot_message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/helthcheck.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16proto/helthcheck.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13proto/message.proto2[\n\x0bhealthCheck\x12L\n\x0bhealthCheck\x12\x16.google.protobuf.Empty\x1a\x0f.proto.Response\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/healthCheckb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,proto_dot_message__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_HEALTHCHECK = _descriptor.ServiceDescriptor(
  name='healthCheck',
  full_name='proto.healthCheck',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=113,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='healthCheck',
    full_name='proto.healthCheck.healthCheck',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=proto_dot_message__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\016\022\014/healthCheck',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEALTHCHECK)

DESCRIPTOR.services_by_name['healthCheck'] = _HEALTHCHECK

# @@protoc_insertion_point(module_scope)
