# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_swagger.options import annotations_pb2 as protoc__gen__swagger_dot_options_dot_annotations__pb2
from proto import message_pb2 as proto_dot_message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/service.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13proto/service.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\x1a,protoc-gen-swagger/options/annotations.proto\x1a\x13proto/message.proto2~\n\x07\x65xample\x12s\n\x05query\x12\x0e.proto.Request\x1a\x0f.proto.Response\"I\x82\xd3\xe4\x93\x02\x15\"\x10/v1/example/{id}:\x01*\x92\x41+b)\n\x0e\n\nApiKeyAuth\x12\x00\n\x17\n\x06OAuth2\x12\r\n\x04read\n\x05writeb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,protoc__gen__swagger_dot_options_dot_annotations__pb2.DESCRIPTOR,proto_dot_message__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_EXAMPLE = _descriptor.ServiceDescriptor(
  name='example',
  full_name='proto.example',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=127,
  serialized_end=253,
  methods=[
  _descriptor.MethodDescriptor(
    name='query',
    full_name='proto.example.query',
    index=0,
    containing_service=None,
    input_type=proto_dot_message__pb2._REQUEST,
    output_type=proto_dot_message__pb2._RESPONSE,
    serialized_options=_b('\202\323\344\223\002\025\"\020/v1/example/{id}:\001*\222A+b)\n\016\n\nApiKeyAuth\022\000\n\027\n\006OAuth2\022\r\n\004read\n\005write'),
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLE)

DESCRIPTOR.services_by_name['example'] = _EXAMPLE

# @@protoc_insertion_point(module_scope)
