=begin
#An example of generating swagger via gRPC ecosystem.

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Contact: none@example.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::V1ExampleServiceQueryRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::V1ExampleServiceQueryRequest do
  let(:instance) { OpenapiClient::V1ExampleServiceQueryRequest.new }

  describe 'test an instance of V1ExampleServiceQueryRequest' do
    it 'should create an instance of V1ExampleServiceQueryRequest' do
      expect(instance).to be_instance_of(OpenapiClient::V1ExampleServiceQueryRequest)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
